### ISSUE TITLE
UDF Error with Credit Card Fraud Detection

### ISSUE THREAD

**Issue by snowflakehanbing** [Snowflake-Labs/snowpark-python-demos#12]
I am running through credit card fraud detection snowpark exercises, everything looks good except I am getting an error when i try to use query with the new UDF.

**Failed Query In Snowsight:**
 SELECT TRANSACTION_ID, TX_DATETIME, CUSTOMER_ID, TERMINAL_ID, TX_AMOUNT ,detect_fraud_batch_udf(TX_AMOUNT,TX_DURING_WEEKEND, TX_DURING_NIGHT, CUST_CNT_TX_1, CUST_AVG_AMOUNT_1, CUST_CNT_TX_7, CUST_AVG_AMOUNT_7, CUST_CNT_TX_30,CUST_AVG_AMOUNT_30, NB_TX_WINDOW_1, TERM_RISK_1, NB_TX_WINDOW_7,TERM_RISK_7, NB_TX_WINDOW_30,TERM_RISK_30) AS FRAUD_PROB 
FROM CUSTOMER_TRX_FRAUD_FEATURES 
WHERE TX_DATETIME > '2019-07-15 00:00:00' LIMIT 10;

**100357 (P0000): Python Interpreter Error:**
Traceback (most recent call last):
  File "_udf_code.py", line 32, in compute
  File "_udf_code.py", line 21, in wrapper
  File "/var/folders/ck/ll2bz1_s3ng7w67zf6mdvqh40000gn/T/ipykernel_77660/546210058.py", line 17, in detect_fraud_batch
  File "/Users/hayan/opt/anaconda3/envs/snowpark_070/lib/python3.8/site-packages/cachetools/__init__.py", line 641, in wrapper
  File "/var/folders/ck/ll2bz1_s3ng7w67zf6mdvqh40000gn/T/ipykernel_77660/546210058.py", line 10, in read_file
  File "/usr/lib/python_udf/5dd4a97c20bf6b6243e739c66c4fbfa80ab53172655f7f15cf1c55d0f462ae66/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 577, in load
    obj = _unpickle(fobj)
  File "/usr/lib/python_udf/5dd4a97c20bf6b6243e739c66c4fbfa80ab53172655f7f15cf1c55d0f462ae66/lib/python3.8/site-packages/joblib/numpy_pickle.py", line 506, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python_udf/5dd4a97c20bf6b6243e739c66c4fbfa80ab53172655f7f15cf1c55d0f462ae66/lib/python3.8/pickle.py", line 1212, in load
    dispatch[key[0]](self)
KeyError: 255
 in function DETECT_FRAUD_BATCH_UDF with handler compute

**Comment by snowflakehanbing** [comment]
@cachetools.cached(cache={})
def read_file(filename):
    import joblib
    import sys
    import os
    
    import_dir = sys._xoptions.get("snowflake_import_directory")
    if import_dir:
        with open(os.path.join(import_dir, filename), 'rb') as file:
            m = joblib.load(file)
            return m

@F.udf(name = 'detect_fraud_batch_udf', is_permanent = True, replace = True, stage_location = '@UDFSTAGE')
def detect_fraud_batch(df: PandasDataFrame[float, int, int, int, float, int, float, int, float, int, float, int, float, int, float]) -> PandasSeries[float]:
    import sklearn
    
    pipeline = read_file('predict_fraud.joblib')
    return pipeline.predict_proba(df)[:,1]

**Comment by snowflakehanbing** [comment]
Snowpark Version is 0.7.0

**Comment by sfc-gh-mstellwall** [comment]
Please use the GA version, 1.0.0, or a version newer than 0.7.0, the demo works with version 0.8.0 and newer.
